import Head from 'next/head';

export default function test() {
  return (
    <div>
      <Head>
        <title>Monochrome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"></link>
      </Head>
      Hello
      <i className="fa-solid fa-phone"></i>
      <button className="button">test</button>
      <button className="button button-large">large test</button>
      <span className="badge"></span>
    </div>
  );
}
